# Generated by Django 4.2.4 on 2023-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cargo',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='Position_company',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Puesto en compañia'),
        ),
        migrations.AddField(
            model_name='user',
            name='Position_company',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Puesto en compañia'),
        ),
    ]
