# Generated by Django 4.2.4 on 2023-09-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_historicaluser_cargo_remove_user_cargo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='Position',
            new_name='Position_company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Position',
            new_name='Position_company',
        ),
    ]
